### ISSUE TITLE
prism integration not working

### ISSUE THREAD

**Issue by anovickis** [Zarius/Bukkit-OtherBlocks#321]
I have Mc 1.64 + 
MCPC+ latest (MCPC+ version git-MCPC-Plus-jenkins-MCPC-Plus-164-250 (MC: 1.6.4) (Implementing API version 1.6.4-R2.1-SNAPSHOT)
)

and  Prism version 2.0Beta6-MCPC-MC1.6-20-g300224e-SNAPSHOT

see below "Caused by: java.lang.NoSuchFieldError: actionsRecorder"

13:42:47 [INFO] [OtherDrops:2.8b.566] PerformDrop: scheduling THIS
13:42:47 [INFO] [OtherDrops:2.8b.566] Tool damaged.
13:42:47 [INFO] [OtherDrops:2.8b.566] PerformDrop: scheduling GLASS
13:42:47 [INFO] [OtherDrops:2.8b.566] PerformDrop: blockbreak or fishing - not default drop - cancelling event (dropcount=2).
13:42:47 [SEVERE] Could not pass event BlockBreakEvent to OtherDrops v2.8b.566
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:437)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:31)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:807)
        at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:77)
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:472)
        at net.minecraft.item.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:361)
        at net.minecraft.item.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:302)
        at net.minecraft.network.NetServerHandler.func_72510_a(NetServerHandler.java:790)
        at net.minecraft.network.packet.Packet14BlockDig.func_73279_a(Packet14BlockDig.java:67)
        at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:470)
        at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:233)
        at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
        at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:34)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.NoSuchFieldError: actionsRecorder
        at com.gmail.zariust.otherdrops.Dependencies.queueBlockBreak(Dependencies.java:306)
        at com.gmail.zariust.otherdrops.OtherDrops.clearDrops(OtherDrops.java:387)
        at com.gmail.zariust.otherdrops.OtherDrops.performDrop(OtherDrops.java:316)
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:435)
        ... 20 more
13:42:52 [INFO] [OtherDrops:2.8b.566] PerformDrop - potential drops found: [BREAK on ANY_CREATURE drops DENY] tool: [LAVA]
1

**Comment by israelcurtis** [comment]
[bump] we'd sure love to be able to use prism and otherdrops together again -- but still getting the same block break error, using latest otherdrops dev build and latest prism 2.0.4

Could we get an update?

http://pastebin.com/1uVKtz3G
