### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TomPiXX** [Zarius/Bukkit-OtherBlocks#345]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:15:54 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:15:56 INFO]: [TomXPro: Given [Fresh Water] * 4 to TomXPro]
[22:16:18 INFO]: Unbekannter Befehl. Bitte gib "/hilfe" ein um Hilfe zu erhalten.
[22:16:53 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:16:53 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:16:59 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:17:02 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:17:22 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:17:34 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:17:44 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more
[22:19:30 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cau
ldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-
Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet,
but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java
:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-C
auldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 12 more

**Comment by bheiskell** [comment]
I believe this was fixed in f84169e28c0e227ec78b29e5f16be6d2f154bb2b

**Comment by Zarius** [comment]
Yes, thanks for noting this :)
