### ISSUE TITLE
new PlayerDeathEvent (possibly more) error in 1.8 and latest 2.8b596

### ISSUE THREAD

**Issue by israelcurtis** [Zarius/Bukkit-OtherBlocks#350]
```08.01 15:03:46 [Server] INFO at com.gmail.zariust.otherdrops.event.DropRunner.processActions(DropRunner.java:105) ~[?:?]
08.01 15:03:46 [Server] INFO at com.gmail.zariust.otherdrops.parameters.actions.SoundAction.act(SoundAction.java:133) ~[?:?]
08.01 15:03:46 [Server] INFO at com.gmail.zariust.otherdrops.parameters.actions.SoundAction.process(SoundAction.java:150) ~[?:?]
08.01 15:03:46 [Server] INFO at com.gmail.zariust.otherdrops.parameters.actions.SoundAction.playSound(SoundAction.java:195) ~[?:?]
08.01 15:03:46 [Server] INFO Caused by: java.lang.NullPointerException
08.01 15:03:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:757) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1412) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.World.g(World.java:1565) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1590) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityCreeper.s_(EntityCreeper.java:104) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityCreeper.cp(EntityCreeper.java:214) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.WorldServer.createExplosion(WorldServer.java:1003) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.World.createExplosion(World.java:1843) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.Explosion.a(Explosion.java:132) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityPlayer.damageEntity(EntityPlayer.java:486) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityHuman.damageEntity(EntityHuman.java:801) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:774) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at net.minecraft.server.v1_8_R1.EntityPlayer.die(EntityPlayer.java:407) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:381) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8-b18.jar:git-Spigot-e497721-96d09e3]
08.01 15:03:46 [Server] INFO org.bukkit.event.EventException
08.01 15:03:46 [Server] INFO [15:03:46 ERROR]: Could not pass event PlayerDeathEvent to OtherDrops v2.8b.596```

**Comment by Zarius** [comment]
Looks like an error in the play sound function, problem with the config or
possibly a change in Minecraft/Spigot 1.8?
