### ISSUE TITLE
Could not pass event BlockBreakEvent to OtherDrops v2.8b.596 - LogBlock conflict

### ISSUE THREAD

**Issue by CaneCraft** [Zarius/Bukkit-OtherBlocks#357]
OtherDrops version: Both v2.8b.596 and v2.8b.582 for 1.8.1

LogBlock is conflicting with OtherDrops.

[23:23:45 ERROR]: Could not pass event BlockBreakEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:602) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NoSuchMethodError: de.diddiz.LogBlock.Consumer.queueBlockBreak(Ljava/lang/String;Lorg/bukkit/block/BlockState;)V
        at com.gmail.zariust.otherdrops.Dependencies.queueBlockBreak(Dependencies.java:309) ~[?:?]
        at com.gmail.zariust.otherdrops.SectionManager.clearDrops(SectionManager.java:235) ~[?:?]
        at com.gmail.zariust.otherdrops.SectionManager.performDrop(SectionManager.java:164) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:109) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        ... 16 more

Config (if applicable):
Happens on anything, even the most basic stuff.
    BOOKSHELF:
        - tool: ANY_AXE
          drop: BOOKSHELF

Disabling LogBlock makes OtherDrops work just fine. I don't think there's a way I can personally fix this though.

**Comment by frymaster** [comment]
@CaneCraft - I'm a dev for LogBlock

This is because in the newer versions of LB, the old methods for queuing a log entry (where the player was identified by name) were replaced with versions where the player is identified by UUID.  While plugins that hook into LogBlock *should* update to use the new methods, getting rid of the old ones entirely broke them unnecessarily.

I'm looking for testers for an update to LogBlock that reintroduces the old methods (but discourages devs from writing new code that uses them).  Are you willing to download the dev version linked in LogBlock/LogBlock#621 and see if it works OK?
