### ISSUE TITLE
LeavesDecayEvent

### ISSUE THREAD

**Issue by FioletowyAka** [Zarius/Bukkit-OtherBlocks#360]
Bukkit 1.7.2 r0.3

[12:41:02] [Server thread/ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:486) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:471) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.BlockLeaves.e(BlockLeaves.java:127) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.BlockLeaves.a(BlockLeaves.java:118) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.WorldServer.g(WorldServer.java:403) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.WorldServer.doTick(WorldServer.java:207) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:629) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java:62) ~[?:?]
	at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
	... 12 more

**Comment by Brunner2** [comment]
I've the same (spigot 1.7.10 build 1657)

**Comment by Zarius** [comment]
Noting still an issue under Spigot 1.8.8 - to be tested soon with newest build.
