### ISSUE TITLE
Permission condition error

### ISSUE THREAD

**Issue by Fargaze** [Zarius/Bukkit-OtherBlocks#390]
```
    RED_FLOWER:0:
        - drop: {392@!~&fBlack Pepper/1-3%/100%, 392@!~&fWhite Pepper/1-2/10%}
          lorename: "&fPruning Shears"
          biome: PLAINS
          permission: [Gathering]
```

Issue occurs only when permission is added to the drop.

```
[19:19:05] [Server thread/INFO]: [PermissionsEx] User "f27701b0-1316-4fee-938b-d3df3f5d6345" get timed permission "otherdrops.custom.Gathering"  from Fargaze
[19:19:07] [Server thread/INFO]: [OtherDrops:2.8b-dev.1375] PerformDrop - potential drops found: [BREAK on RED_ROSE@ drops {POTATO_ITEM, POTATO_ITEM/1~2/10.0%}] tool: PLAYER@Fargaze with SHEARS@93/1
[19:19:07] [Server thread/ERROR]: Could not pass event BlockBreakEvent to OtherDrops v2.8b-dev.1375
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:193) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:832) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
    at com.gmail.zariust.otherdrops.event.CustomDrop.hasPermission(CustomDrop.java:559) ~[?:?]
    at com.gmail.zariust.otherdrops.event.CustomDrop.matches(CustomDrop.java:164) ~[?:?]
    at com.gmail.zariust.otherdrops.SectionManager.gatherDrops(SectionManager.java:332) ~[?:?]
    at com.gmail.zariust.otherdrops.SectionManager.performDrop(SectionManager.java:125) ~[?:?]
    at com.gmail.zariust.otherdrops.listener.OdBlockListener.onBlockBreak(OdBlockListener.java:109) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    ... 17 more
```

**Comment by ghost** [comment]
Set this:

> RED_FLOWER:0:
>        - drop: {392@!~&fBlack Pepper/1-3%/100%, 392@!~&fWhite Pepper/1-2/10%}
>          lorename: "&fPruning Shears"
>          biome: PLAINS
>          permission: [Gathering]

to

> RED_FLOWER:0:
>        - drop: {392@!~&fBlack Pepper/1-3%/100%, 392@!~&fWhite Pepper/1-2/10%}
>          lorename: "&fPruning Shears"
>          biome: PLAINS
>          permission: gathering
