### ISSUE TITLE
OtherDrop failed to load WorldGuard

### ISSUE THREAD

**Issue by yeyifangg** [Zarius/Bukkit-OtherBlocks#392]
OD version 2.8b.582
WorldGuard version 6.1

[20:45:52 ERROR]: Could not pass event LeavesDecayEvent to OtherDrops v2.8b.582
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.block.BlockLeaves.func_150126_e(BlockLeaves.java:229) [alt.class:?]
        at net.minecraft.block.BlockLeaves.func_149674_a(BlockLeaves.java:207) [alt.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:569) [mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:288) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.checkWorldguardLeafDecayPermission(OdBlockListener.java:62) ~[?:?]
        at com.gmail.zariust.otherdrops.listener.OdBlockListener.onLeavesDecay(OdBlockListener.java:78) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        ... 12 more

**Comment by yeyifangg** [comment]
Hmm，seems to be duplicate with #387
