### ISSUE TITLE
Console Spam org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)

### ISSUE THREAD

**Issue by khamseen** [Zarius/Bukkit-OtherBlocks#396]
I'm getting this spamming in our console. It shows up once during bootup and then periodically throughout the day. Seems to coincide with when people do things which will trigger the drops.

[16:41:04] [Craft Scheduler Thread - 62/WARN]: Exception in thread "Craft Scheduler Thread - 62" 
[16:41:04] [Craft Scheduler Thread - 62/WARN]: org.apache.commons.lang.UnhandledException: Plugin OtherDrops v2.8b.582 generated an exception while executing task 21
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.gmail.zariust.otherdrops.metrics.Metrics.postPlugin(Metrics.java:334)
    at com.gmail.zariust.otherdrops.metrics.Metrics.access$400(Metrics.java:57)
    at com.gmail.zariust.otherdrops.metrics.Metrics$1.run(Metrics.java:222)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

Running on Spigot build for 1.9.2

I'm also finding that no mobs are dropping items I've added to them, block drops seem to be working correctly but just no monster drops even if I set them to 100% chance.

Here's a copy of my drops.yml
http://pastebin.com/gp2q3it2

**Comment by khamseen** [comment]
I was able to get this working by using PDevil's fork to build a new file from.
